# Required: local settings
local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# Required: deployment targets
targets:
  - type     : "awss3"
    access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>

# Required: packages to be deployed
packages:
  - name     : "snowflake-loader-assets"
    bucket   : "snowplow-hosted-assets"                    # TODO: Change
    path     : "4-storage/snowplow-badrows"    # TODO: Change
    region   : "eu-west-1"


    # Will attempt to overwrite a published entity if one is found
    override : false

    # If the artifact already exists will determine whether or not to fail the release
    continue_on_conflict : false

    # The version of this package
    version  : <%= ENV['TRAVIS_TAG'] %>

    # Required IF '--check-version' is passed: will assert that both versions are the same
    build_version : <%= FUNC['sbt_version(.)'] %>

    build_commands:
      - sbt assembly

    # Required: Artifact
    artifacts:
        # The artifact name is composed like so: {{prefix}}{{version}}{{suffix}}.zip
      - type   : "asis"
        prefix : "snowplow-badrows-"
        suffix : ".jar"

        # The binaries to put in the zip
        binary_paths:
          - target/scala-2.11/snowplow-badrows-<%= ENV['TRAVIS_TAG'] %>.jar
